server:
  port: 8443
  ssl:
    enabled: true
    # certificate: ${HOME}/.config/devcerts/wallet-cert.pem
    # certificate-private-key: ${HOME}/.config/devcerts/wallet-key.pem
    key-store-type: JKS
    key-store: "file:../eudiw-prototype/sc-environment/config/common/tls.jks"
    key-store-password: secret
    key-alias: tls


spring:
  ssl:
    bundle:
      pem:
        rest:
          truststore:
            # certificate path works in local sc-environment if the repos are located side by side
            # otherwise: set the filepath with SPRING_SSL_BUNDLE_PEM_REST_TRUSTSTORE_CERTIFICATE environment variable
            certificate: file:../eudiw-prototype/sc-environment/config/common/tls.crt

eudiw:
  issuer: https://local.dev.swedenconnect.se:8443
  issuerBaseUrl: https://local.dev.swedenconnect.se:8443
  authHost: https://local.dev.swedenconnect.se:8443
  credentialHost: https://local.dev.swedenconnect.se:8443
  expHours: 24
  clientId: eudiw-client
  oidFederationBaseUrl:  https://local.dev.swedenconnect.se:9040/oidfed
  issuerSignerKeyPemFile: issuer-jwt-ec256-key-pair.pem
  redirectUris:
    - "https://local.dev.swedenconnect.se:8443/callback-test-1-authorisation-flow"
    - "https://local.dev.swedenconnect.se:8443"

  swedenconnect:
    base-url: https://local.dev.swedenconnect.se:9060/id-backend/auth
    client: wallet-dev
    return-base-url: https://local.dev.swedenconnect.se:8443/auth/return

  token-issuer-cert:
    - cert-location: classpath:dev/tokenSigner.crt
      kid: tokenSigner-1

